### PR TITLE
Several minor bug fixes and warning cleanup

### LINKED ISSUE #80: Crashing with 10i (10j too)
Latest version crashes:

http://hastebin.com/izoxogisic.vhdl

10h works just fine.

### PR DESCRIPTION
**Pull request by Mordenkainen**
Fixes #80

### CODE REVIEW

File: src/main/java/theflogat/technomancy/lib/compat/ModuleBase.java [hunk 1]
```diff
@@ -28,9 +28,11 @@ public static void registerBlock(Block block, String name) {
 		if(block instanceof BlockContainerAdvanced){
 			GameRegistry.registerBlock(block, ItemAdvancedBase.class, name);
 			return;
+		} else {
+			if(block!=null) {
+				GameRegistry.registerBlock(block, name);
+			}
 		}
```
Comment (Mordenkainen) [inline src/main/java/theflogat/technomancy/lib/compat/ModuleBase.java]: OOPS. I didn't mean to commit this. It won't hurt anything, but it's also not really needed.

Comment (theflogat) [inline src/main/java/theflogat/technomancy/lib/compat/ModuleBase.java]: No worries
